GRANT USAGE ON FUNCTION DB_INGESTION_TOOLS_{{environment}}.UTILS.parse_field_type(string, int, int) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON FUNCTION DB_INGESTION_TOOLS_{{environment}}.UTILS.get_table_pk_array(string) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;


GRANT USAGE ON PROCEDURE DB_INGESTION_TOOLS_{{environment}}.STREAMING.CREATE_KAFKA_FLATTEN_VIEW(VARCHAR, VARCHAR) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON PROCEDURE DB_INGESTION_TOOLS_{{environment}}.STREAMING.CREATE_KAFKA_SCHEMA_VIEW(VARCHAR, VARCHAR) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON PROCEDURE DB_INGESTION_TOOLS_{{environment}}.STREAMING.CREATE_GLUE_VIEW(VARCHAR, VARCHAR) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON PROCEDURE DB_INGESTION_TOOLS_{{environment}}.STREAMING.CONSOLIDATE_TABLE_MERGE(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON PROCEDURE DB_INGESTION_TOOLS_{{environment}}.STREAMING.CHECK_NEW_STREAMING_TABLE(VARCHAR, VARCHAR, VARCHAR, VARCHAR, BOOLEAN, BOOLEAN) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON PROCEDURE DB_INGESTION_TOOLS_{{environment}}.STREAMING.UNLOAD_TABLE(int,varchar,varchar,varchar,varchar,varchar) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;


GRANT USAGE ON PROCEDURE DB_INGESTION_TOOLS_{{environment}}.BATCH.SP_GET_ADL_PATH(VARCHAR) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON PROCEDURE DB_INGESTION_TOOLS_{{environment}}.BATCH.SP_LOAD_BATCH_FILE(VARCHAR) TO ROLE {{ environment }}_LND_NA_DEVELOPER_FR;