USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS ECI_INGESTION_TOOLS COMMENT = 'Ingestion tools (tables and procedures) Database';

CREATE SCHEMA IF NOT EXISTS ECI_INGESTION_TOOLS.BATCH;

CREATE SCHEMA IF NOT EXISTS ECI_INGESTION_TOOLS.STREAMING;

CREATE SCHEMA IF NOT EXISTS ECI_INGESTION_TOOLS.UTILS;

GRANT USAGE ON DATABASE  ECI_INGESTION_TOOLS TO ROLE &{ENV}_LND_NA_DEVELOPER_FR; 
GRANT USAGE ON SCHEMA ECI_INGESTION_TOOLS.BATCH TO ROLE &{ENV}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON SCHEMA ECI_INGESTION_TOOLS.STREAMING TO ROLE &{ENV}_LND_NA_DEVELOPER_FR;
GRANT USAGE ON SCHEMA ECI_INGESTION_TOOLS.UTILS TO ROLE &{ENV}_LND_NA_DEVELOPER_FR;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA ECI_INGESTION_TOOLS.UTILS TO ROLE &{ENV}_LND_NA_DEVELOPER_FR;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA ECI_INGESTION_TOOLS.STREAMING TO ROLE &{ENV}_LND_NA_DEVELOPER_FR;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA ECI_INGESTION_TOOLS.BATCH TO ROLE &{ENV}_LND_NA_DEVELOPER_FR;