USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS ECI_INGESTION_TOOLS COMMENT = 'Ingestion tools (tables and procedures) Database';

CREATE SCHEMA IF NOT EXISTS ECI_INGESTION_TOOLS.BATCH;

CREATE SCHEMA IF NOT EXISTS ECI_INGESTION_TOOLS.STREAMING;

CREATE SCHEMA IF NOT EXISTS ECI_INGESTION_TOOLS.UTILS;