USE DATABASE DB_LND_{{environment}};
USE ROLE SYSADMIN;
USE SCHEMA AUTOMATION;

CREATE OR REPLACE TASK TSK_CHECK_NEW_DMP_DM3_GLUE_Z001 WAREHOUSE = {{warehouse}} SCHEDULE = 'USING CRON 0 * * * * UTC' AS 
    call DB_INGESTION_TOOLS_{{environment}}.STREAMING.SP_CHECK_NEW_STREAMING_TABLE('DB_LND_{{environment}}', 'SAP_DMP_DM3_GLUE', 'Z001_', '_CONSOLIDATED', TRUE, TRUE);
CREATE OR REPLACE TASK TSK_CHECK_NEW_DMP_DM3_GLUE_Z003 WAREHOUSE = {{warehouse}} SCHEDULE = 'USING CRON 0 * * * * UTC' AS 
    call DB_INGESTION_TOOLS_{{environment}}.STREAMING.SP_CHECK_NEW_STREAMING_TABLE('DB_LND_{{environment}}', 'SAP_DMP_DM3_GLUE', 'Z003_', '_CONSOLIDATED', TRUE, TRUE);

--GRANT ALL PRIVILEGES ON TASK TSK_CHECK_NEW_DMP_DM3_GLUE_Z001 TO ROLE SYSADMIN;
--GRANT ALL PRIVILEGES ON TASK TSK_CHECK_NEW_DMP_DM3_GLUE_Z003 TO ROLE SYSADMIN;

CALL DB_GOV_SECURITY_DES.RBAC_GRANT.SP_GRANT_OWNERSHIP_ON_TASK('DB_LND_{{environment}}.AUTOMATION.TSK_CHECK_NEW_DMP_DM3_GLUE_Z001', '{{environment}}_LND_AUTOMATION_FR');
CALL DB_GOV_SECURITY_DES.RBAC_GRANT.SP_GRANT_OWNERSHIP_ON_TASK('DB_LND_{{environment}}.AUTOMATION.TSK_CHECK_NEW_DMP_DM3_GLUE_Z003', '{{environment}}_LND_AUTOMATION_FR');

ALTER TASK TSK_CHECK_NEW_DMP_DM3_GLUE_Z001 RESUME;
ALTER TASK TSK_CHECK_NEW_DMP_DM3_GLUE_Z003 RESUME;