USE DATABASE DB_LND_{{environment}};
USE ROLE SYSADMIN;
USE SCHEMA AUTOMATION;

CREATE OR REPLACE TASK TSK_CHECK_NEW_KAKFA_STERLING WAREHOUSE = {{warehouse}} SCHEDULE = 'USING CRON 0 * * * * UTC' AS 
    call CHECK_NEW_STREAMING_TABLE('DB_LND_{{environment}}', 'DB2_STERLING_DB2STERL_CDCKAFKA', 'KAFKA_', '_CONSOLIDATED', FALSE, FALSE);

CALL DB_GOV_SECURITY_DES.RBAC_GRANT.SP_GRANT_OWNERSHIP_ON_TASK('TSK_CHECK_NEW_KAKFA_STERLING', '{{environment}}_LND_AUTOMATION_FR')

ALTER TASK TSK_CHECK_NEW_KAKFA_STERLING RESUME;