variables:
  SF_ACCOUNT: "aa02382.west-europe.azure"
  SF_DATABASE: "ECI_AUTO_STREAMING"
  SF_ROLE: "SNW_CORP_ACCENTURE"
  SF_USERNAME: "X50876MA"
  SF_WAREHOUSE: "SNW_CORP_ACCENTURE"
  SF_PASSWORD: "Danius11"
  ENV: "DEV"